"""
Hide My Email Generator Module

Handles creating new iCloud Hide My Email addresses via Apple's internal API.

API Flow (reverse-engineered from icloud.com web interface):
  1. POST /v1/hme/generate  -> Apple generates a random email address
  2. POST /v1/hme/reserve   -> Reserves/activates the email with a label
  3. GET  /v2/hme/list       -> Lists all HME addresses
  4. POST /v1/hme/deactivate -> Deactivates an HME address
  5. POST /v1/hme/delete     -> Deletes an HME address

Authentication: Session cookies from icloud.com (not API keys)
Rate limits: ~5 emails per 30 minutes per family member, ~700 total cap
"""

import asyncio
import ssl
import urllib.parse
from typing import Dict, List, Optional, Tuple

import aiohttp
import certifi

from icloud_auth import iCloudAuth


class HideMyEmailGenerator:
    """Generates and manages iCloud Hide My Email addresses."""

    def __init__(self, auth: iCloudAuth, proxy_url: Optional[str] = None):
        """Initialize with an authenticated iCloudAuth instance.

        Args:
            auth: An initialized iCloudAuth instance with valid cookies.
            proxy_url: Optional SOCKS5/HTTP proxy URL (e.g., socks5://user:pass@host:port)
        """
        self.auth = auth
        self.host = auth.host
        self.base_url_v1 = f"https://{self.host}/v1/hme"
        self.base_url_v2 = f"https://{self.host}/v2/hme"
        self.params = auth.get_api_params()
        self.headers = auth.get_base_headers()
        self.session: Optional[aiohttp.ClientSession] = None
        self.proxy_url = proxy_url

    async def __aenter__(self):
        ssl_ctx = ssl.create_default_context(cafile=certifi.where())
        
        connector = None
        if self.proxy_url:
            try:
                from aiohttp_socks import ProxyConnector
                # ProxyConnector handles socks5:// and http:// transparently
                connector = ProxyConnector.from_url(self.proxy_url, ssl=ssl_ctx)
                print(f"🔗 [iCloud HME] Using proxy: {self.proxy_url.split('@')[-1] if '@' in self.proxy_url else self.proxy_url}")
            except ImportError:
                print("⚠️ [iCloud HME] aiohttp-socks not installed, ignoring proxy. Run: pip install aiohttp-socks")
                connector = aiohttp.TCPConnector(ssl=ssl_ctx)
        else:
            connector = aiohttp.TCPConnector(ssl=ssl_ctx)
            
        self.session = aiohttp.ClientSession(
            headers=self.headers,
            timeout=aiohttp.ClientTimeout(total=15),
            connector=connector,
        )
        return self

    async def __aexit__(self, exc_t, exc_v, exc_tb):
        if self.session:
            await self.session.close()
            self.session = None

    # ------------------------------------------------------------------
    # Core API Methods
    # ------------------------------------------------------------------

    async def generate_email(self) -> Dict:
        """Step 1: Request Apple to generate a random HME address.

        POST /v1/hme/generate
        Body: {"langCode": "en-us"}

        Returns:
            API response dict. On success:
            {
                "success": true,
                "result": {
                    "hme": "random-words@icloud.com"
                }
            }
        """
        url = f"{self.base_url_v1}/generate"
        payload = {"langCode": "en-us"}

        try:
            async with self.session.post(url, params=self.params, json=payload) as resp:
                data = await resp.json(content_type=None)
                if not isinstance(data, dict):
                    return {"success": False, "error": {"errorMessage": f"Invalid API response format: {type(data).__name__}"}}
                return data
        except asyncio.TimeoutError:
            return {"success": False, "error": {"errorMessage": "Request timed out"}}
        except Exception as e:
            return {"success": False, "error": {"errorMessage": str(e)}}

    async def reserve_email(self, email: str, label: str = "", note: str = "") -> Dict:
        """Step 2: Reserve/activate a generated HME address.

        POST /v1/hme/reserve
        Body: {"hme": "...", "label": "...", "note": "..."}

        Args:
            email: The generated email address to reserve.
            label: Label for the email (shown in iCloud settings).
            note: Optional note attached to the email.

        Returns:
            API response dict. On success: {"success": true, ...}
        """
        url = f"{self.base_url_v1}/reserve"
        config = self.auth.config
        label = label or config.get("hme_label_prefix", "auto-generated")
        note = note or config.get("hme_note", "Generated by automation tool")

        # Apple uses the email itself as the label if label contains the email
        payload = {
            "hme": email,
            "label": f"{label}-{email.split('@')[0]}" if label else email,
            "note": note,
        }

        try:
            async with self.session.post(url, params=self.params, json=payload) as resp:
                data = await resp.json(content_type=None)
                if not isinstance(data, dict):
                    return {"success": False, "error": {"errorMessage": f"Invalid API response format: {type(data).__name__}"}}
                return data
        except asyncio.TimeoutError:
            return {"success": False, "error": {"errorMessage": "Request timed out"}}
        except Exception as e:
            return {"success": False, "error": {"errorMessage": str(e)}}

    async def list_emails(self) -> Dict:
        """List all Hide My Email addresses.

        GET /v2/hme/list

        Returns:
            API response dict containing hmeEmails array.
        """
        url = f"{self.base_url_v2}/list"

        try:
            async with self.session.get(url, params=self.params) as resp:
                data = await resp.json(content_type=None)
                if not isinstance(data, dict):
                    return {"success": False, "error": {"errorMessage": f"Invalid API response format: {type(data).__name__}"}}
                return data
        except asyncio.TimeoutError:
            return {"success": False, "error": {"errorMessage": "Request timed out"}}
        except Exception as e:
            return {"success": False, "error": {"errorMessage": str(e)}}

    async def deactivate_email(self, anonymous_id: str) -> Dict:
        """Deactivate an active HME address.

        POST /v1/hme/deactivate
        Body: {"anonymousId": "..."}

        Args:
            anonymous_id: The anonymousId of the HME entry to deactivate.

        Returns:
            API response dict.
        """
        url = f"{self.base_url_v1}/deactivate"
        payload = {"anonymousId": anonymous_id}

        try:
            async with self.session.post(url, params=self.params, json=payload) as resp:
                data = await resp.json(content_type=None)
                if not isinstance(data, dict):
                    return {"success": False, "error": {"errorMessage": f"Invalid API response format: {type(data).__name__}"}}
                return data
        except asyncio.TimeoutError:
            return {"success": False, "error": {"errorMessage": "Request timed out"}}
        except Exception as e:
            return {"success": False, "error": {"errorMessage": str(e)}}

    async def delete_email(self, anonymous_id: str) -> Dict:
        """Delete an HME address (must be deactivated first).

        POST /v1/hme/delete
        Body: {"anonymousId": "..."}

        Args:
            anonymous_id: The anonymousId of the HME entry to delete.

        Returns:
            API response dict.
        """
        url = f"{self.base_url_v1}/delete"
        payload = {"anonymousId": anonymous_id}

        try:
            async with self.session.post(url, params=self.params, json=payload) as resp:
                data = await resp.json(content_type=None)
                if not isinstance(data, dict):
                    return {"success": False, "error": {"errorMessage": f"Invalid API response format: {type(data).__name__}"}}
                return data
        except asyncio.TimeoutError:
            return {"success": False, "error": {"errorMessage": "Request timed out"}}
        except Exception as e:
            return {"success": False, "error": {"errorMessage": str(e)}}

    # ------------------------------------------------------------------
    # High-Level Operations
    # ------------------------------------------------------------------

    async def create_email(self, label: str = "", note: str = "") -> Tuple[bool, str, str]:
        """Full flow: Generate + Reserve a new Hide My Email address.

        Args:
            label: Optional label for the email.
            note: Optional note for the email.

        Returns:
            Tuple of (success, email_address, error_message).
        """
        # Step 1: Generate
        gen_res = await self.generate_email()

        if not gen_res.get("success"):
            err = _extract_error(gen_res)
            return False, "", f"Generate failed: {err}"

        email = gen_res["result"]["hme"]

        # Step 2: Reserve
        reserve_res = await self.reserve_email(email, label=label, note=note)

        if not reserve_res.get("success"):
            err = _extract_error(reserve_res)
            return False, email, f"Reserve failed for {email}: {err}"

        return True, email, ""

    async def create_emails_batch(
        self, count: int, label: str = "", note: str = "", delay: float = 1.0
    ) -> List[str]:
        """Create multiple HME addresses with rate-limit-aware delays.

        Apple rate limits: ~5 emails per 30 minutes per family member.
        We use sequential creation with delays to avoid hitting limits.

        Args:
            count: Number of emails to generate.
            label: Label prefix for emails.
            note: Note for emails.
            delay: Seconds to wait between each creation.

        Returns:
            List of successfully created email addresses.
        """
        created = []
        consecutive_failures = 0

        for i in range(count):
            success, email, error = await self.create_email(label=label, note=note)

            if success:
                created.append(email)
                consecutive_failures = 0
            else:
                consecutive_failures += 1
                # If we hit rate limit (5 consecutive failures), wait longer
                if consecutive_failures >= 3:
                    # Wait 5 minutes before retrying
                    await asyncio.sleep(300)
                    consecutive_failures = 0

            if i < count - 1:
                await asyncio.sleep(delay)

        return created

    async def get_all_emails(self) -> List[Dict]:
        """Get all HME email entries with their details.

        Returns:
            List of email entry dicts with fields:
            - anonymousId: str
            - hme: str (the email address)
            - label: str
            - isActive: bool
            - createTimestamp: int (unix ms)
            - forwardToEmail: str
        """
        res = await self.list_emails()
        if res.get("success") and "result" in res:
            return res["result"].get("hmeEmails", [])
        return []

    async def cleanup_email(self, anonymous_id: str) -> Tuple[bool, str]:
        """Deactivate and delete a single HME address.

        Args:
            anonymous_id: The anonymousId of the HME entry.

        Returns:
            Tuple of (success, message).
        """
        # Deactivate first
        deact_res = await self.deactivate_email(anonymous_id)
        if not deact_res.get("success"):
            err = _extract_error(deact_res)
            # It might already be inactive, try deleting anyway
            if "already" not in err.lower():
                return False, f"Deactivation failed: {err}"

        await asyncio.sleep(0.5)

        # Then delete
        del_res = await self.delete_email(anonymous_id)
        if not del_res.get("success"):
            err = _extract_error(del_res)
            return False, f"Deletion failed: {err}"

        return True, "Successfully deactivated and deleted."


def _extract_error(response: Dict) -> str:
    """Extract human-readable error from API response.

    Args:
        response: The API response dict.

    Returns:
        Error message string.
    """
    error = response.get("error", {})

    if isinstance(error, dict):
        return error.get("errorMessage", "Unknown error")
    elif isinstance(error, int):
        return response.get("reason", f"Error code: {error}")
    elif isinstance(error, str):
        return error
    return "Unknown error"
